[workspace]
resolver = "2"
members = ["icrc7", "archive"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
strip = "debuginfo"
codegen-units = 1
